import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const nodeLabelSource = read('../src/components/CollectionNodeLabel.vue')
const panelSource = read('../src/components/CollectionCascadePanel.vue')
const selectSource = read('../src/components/CollectionSingleSelect.vue')
const interfaceEditSource = read('../src/components/InterfaceEditDialog.vue')
const interfacesSource = read('../src/views/Interfaces.vue')
const casesSource = read('../src/views/InterfaceCases.vue')
const importTargetSource = read('../src/components/ImportTargetPicker.vue')
const generationScopeSource = read('../src/components/InterfaceCaseGenerationScopePanel.vue')

assert.match(nodeLabelSource, /getCollectionStatusType/, '公共节点展示应使用统一的接口集状态规则')
assert.match(nodeLabelSource, /interface_count/, '公共节点展示应显示接口数量')
assert.match(panelSource, /collectionTree/, '多级选择面板应接收接口集树')
assert.match(panelSource, /disabledIds/, '多级选择面板应支持禁用接口集')
assert.match(panelSource, /displayMode: \{ type: String, default: 'cascade' \}/, '公共面板应默认保持逐级展示')
assert.match(panelSource, /displayMode === 'tree'/, '公共面板应支持按场景启用树形展示')
assert.match(panelSource, /<el-tree/, '树形展示应复用 Element Plus 树组件')
assert.match(panelSource, /expand-on-click-node="false"/, '树形单选点击节点时不应误触发展开')
assert.match(panelSource, /\.collection-cascade-panel__tree-option\s*\{[\s\S]*?padding:\s*5px 8px 5px 8px;/, '树形选中行左侧应与边框保持呼吸空间')
assert.match(panelSource, /currentNodes = computed/, '多级选择面板应只展示当前层级节点')
assert.match(panelSource, /activePathNodes = computed/, '多级选择面板应维护当前逐级导航路径')
assert.match(panelSource, /function goToPath/, '多级选择面板应支持通过路径返回上级')
assert.doesNotMatch(panelSource, /columns = computed/, '多级选择面板不应同时铺开所有层级')
assert.doesNotMatch(panelSource, /collection-cascade-panel__column/, '多级选择面板不应依赖多列横向布局')
assert.match(panelSource, /collection-cascade-panel__breadcrumb/, '多级选择面板应展示当前路径')
assert.match(panelSource, /class="collection-cascade-panel__selection"/, '单选场景应保留明确的选中标记')
assert.doesNotMatch(panelSource, /showSelectionControl/, '单选级联面板不应通过隐藏控制项破坏父级展开')
assert.match(panelSource, /collection-cascade-panel__selection-dot/, '自定义单选面板应保留单选标记')
assert.match(panelSource, /function expandNode/, '单选场景应通过右侧箭头展开下级接口集')
assert.match(panelSource, /\.collection-cascade-panel__viewport\s*\{[\s\S]*?width:\s*100%;[\s\S]*?overflow-y:\s*auto;/, '逐级面板应固定在弹层宽度内并只纵向滚动')
assert.match(selectSource, /CollectionCascadePanel/, '单选触发器应复用多级选择面板')
assert.match(selectSource, /displayMode: \{ type: String, default: 'cascade' \}/, '单选选择器应支持可选展示模式')
assert.match(selectSource, /:display-mode="displayMode"/, '单选选择器应向公共面板传递展示模式')
assert.match(selectSource, /<el-cascader/, '单选选择器应支持复用接口集筛选器的级联展示')
assert.match(selectSource, /multiple:\s*false/, '单选级联展示应明确关闭多选')
assert.match(selectSource, /checkStrictly:\s*true/, '单选级联展示应允许选择任意层级接口集')
assert.match(selectSource, /showPrefix:\s*false/, '单选级联展示不应显示会误导交互的单选前缀')
assert.match(selectSource, /checkOnClickNode:\s*false/, '级联节点点击不应代替右侧箭头展开下一级')
assert.match(selectSource, /collection-single-select__cascader-option/, '级联节点内容区域应负责选中当前层级')
assert.match(selectSource, /el-cascader-node__postfix[\s\S]*width:\s*44px/, '级联右侧箭头应扩大可点击区域')
assert.doesNotMatch(selectSource, /showSelectionMarker|collection-single-select__cascader-selection/, '级联选项不应额外占用空间显示选中标记')
assert.match(selectSource, /:show-all-levels="showAllLevels"/, '单选级联回显应支持按场景控制接口集层级')
assert.match(interfaceEditSource, /display-mode="cascader"/, '接口编辑所属接口集应使用级联展示')
assert.doesNotMatch(interfaceEditSource, /show-selection-marker/, '接口详情不应额外显示方形级联选中标记')
assert.doesNotMatch(interfaceEditSource, /display-mode="tree"/, '接口编辑所属接口集不应使用全展开树形展示')
assert.match(interfaceEditSource, /collection-single-select__cascader[\s\S]*width:\s*100%/, '接口编辑所属接口集应与上下输入框保持同宽')
assert.doesNotMatch(selectSource, /show-selection-control/, '接口集单选触发器应使用面板默认的单选交互')
assert.match(selectSource, /width:\s*max-content/, '选择器弹层宽度应随实际层级收紧')
assert.match(selectSource, /selectedNode\?\.name/, '选择器闭合状态应只展示当前接口集名称')
assert.match(selectSource, /:title="selectedPath/, '选择器闭合状态应通过悬停保留完整层级路径')
assert.doesNotMatch(selectSource, /@click="open"/, '点击触发应只保留 Element Plus 的 click 触发机制')
assert.match(selectSource, /defineExpose\(\{\s*close\s*\}\)/, '接口集选择器应向父弹窗暴露关闭弹层的方法')
assert.match(interfacesSource, /CollectionNodeLabel/, '接口管理页应复用公共节点展示')
assert.match(interfacesSource, /CollectionSingleSelect/, '接口管理页单选场景应复用公共选择器')
assert.match(interfaceEditSource, /ref="interfaceCollectionSelectRef"/, '接口详情弹窗应持有所属接口集选择器引用')
assert.match(interfaceEditSource, /@closed="handleClosed"/, '接口详情弹窗关闭时应清理所属接口集弹层')
assert.match(interfaceEditSource, /interfaceCollectionSelectRef\.value\?\.close\(\)/, '接口详情弹窗关闭时应调用所属接口集选择器的关闭方法')
assert.match(casesSource, /CollectionSingleSelect/, '用例管理页应使用新的单选接口集选择器')
assert.match(casesSource, /cards-grid[^>]*:class/, '用例空状态应通过容器状态控制布局')
assert.match(casesSource, /\.cards-grid\.is-empty/, '用例空状态应占满内容区并居中')
assert.match(importTargetSource, /CollectionCascadePanel/, '导入目标选择应复用多级选择面板')
assert.match(importTargetSource, /display-mode="tree"/, '导入目标选择应启用树形展示')
assert.doesNotMatch(importTargetSource, /show-selection-control/, '导入目标选择应使用单选交互')
assert.match(importTargetSource, /collection-picker-panel[\s\S]*collection-cascade-panel__viewport/, '导入目标选择应使用局部级联布局')
assert.doesNotMatch(importTargetSource, /collection-cascade-panel__column/, '导入目标选择不应保留多列布局覆盖')
assert.match(importTargetSource, /\.collection-target-main\s*\{[\s\S]*?flex:\s*1 1 0;[\s\S]*?min-width:\s*0;/, '导入目标主区域应允许路径收缩')
assert.match(importTargetSource, /\.collection-target-copy\s*\{[\s\S]*?flex:\s*1 1 auto;[\s\S]*?width:\s*0;/, '导入目标文字容器应把剩余宽度交给省略文本')
assert.match(importTargetSource, /\.collection-target-path\s*\{[\s\S]*?display:\s*block;[\s\S]*?min-width:\s*0;[\s\S]*?max-width:\s*100%;/, '导入目标路径过长时应只从右侧省略')

assert.match(interfacesSource, /show-checkbox/, '批量删除接口集仍应保留多选能力')
assert.match(generationScopeSource, /multiple: true/, '用例生成范围筛选仍应保留多选配置')

console.log('collection selector contract test ok')
