import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const requestTabs = read('../src/components/RequestConfigTabs.vue')
const interfaceCases = read('../src/views/InterfaceCases.vue')
const testCasesApi = read('../src/api/testcases.js')
const interfaces = read('../src/views/Interfaces.vue')
const batchGenerationDialog = read('../src/components/BatchInterfaceCaseGenerationDialog.vue')
const operationProgress = read('../src/components/AiOperationProgress.vue')
const generationModePicker = read('../src/components/AiGenerationModePickerDialog.vue')
const testCaseEditDialog = read('../src/components/TestCaseEditDialog.vue')
const interfaceEditDialog = read('../src/components/InterfaceEditDialog.vue')
const interfaceDetailDialog = read('../src/components/InterfaceDetailDialog.vue')
const importDialog = read('../src/components/ImportDialog.vue')
const generationComposable = read('../src/composables/useAiImportGeneration.js')
const generationEndpoint = read('../../backend/api/v1/endpoints/import_ai.py')
const generationPolicy = read('../../backend/services/ai_import/generation.py')
const generationPersist = read('../../backend/services/ai_import/persist.py')
const executions = read('../src/views/Executions.vue')
const environments = read('../src/views/Environments.vue')
const requestUtil = read('../src/utils/request.js')
const aiImportApi = read('../src/api/aiImport.js')
const schedulePolicyDialog = executions.match(/<el-dialog\s+v-model="schedulePolicyDialogVisible"[\s\S]*?<\/el-dialog>/)?.[0]

assert.match(requestTabs, /assertion\.enabled !== false/)
assert.match(interfaceCases, /enabled: true/)
assert.match(testCasesApi, /batchConfirmTestCases/)
assert.match(testCasesApi, /\/testcases\/batch-confirm/)
assert.match(interfaceCases, /批量确认/)
assert.match(interfaceCases, /pendingCaseCount/)
assert.match(interfaceCases, /ElMessageBox\.confirm\([\s\S]*待确认[\s\S]*批量确认/)
assert.match(interfaceCases, /batchConfirmTestCases\(currentIfaceId\.value\)/)
assert.match(interfaceCases, /:disabled="!currentIfaceId \|\| pendingCaseCount === 0"/)
assert.match(interfaces, /enabled: true/)
assert.match(executions, /schedulePolicySearch/)
assert.match(executions, /getSchedulePolicies\([\s\S]*page_size/)
assert.ok(schedulePolicyDialog, '执行策略应在独立弹窗中选择')
assert.match(schedulePolicyDialog, /title="选择执行策略"/)
assert.match(schedulePolicyDialog, /<el-pagination[\s\S]*@current-change="loadSchedulePolicies"/)
assert.match(executions, /<el-form-item label="消息发送群"[^>]*:required="form\.auto_execute"/)
assert.match(executions, /<el-form-item label="消息模板"[^>]*:required="form\.auto_execute"/)
assert.match(executions, /class="form-hint">自动执行时至少选择一个有效消息群<\/div>/)
assert.match(executions, /class="form-hint">自动执行时必须选择消息模板<\/div>/)
assert.doesNotMatch(executions, /自动执行至少选择一个有效消息群|自动执行必须选择消息模板/)
assert.doesNotMatch(executions, /消息群和消息模板必须同时配置<\/div>/)
assert.match(executions, /<el-form-item label="描述">[\s\S]*?<el-input v-model="form\.description"[^>]*size="large"/)
assert.doesNotMatch(executions, /v-model="form\.description"[^>]*type="textarea"/)
assert.match(executions, /<el-button[^>]*class="schedule-policy-picker__button"[^>]*@click="openSchedulePolicyDialog"[^>]*>选择执行策略<\/el-button>/)
assert.match(executions, /v-if="selectedSchedulePolicy"[^>]*class="schedule-policy-picker__selected"[\s\S]*?selectedSchedulePolicy\.name/)
assert.match(executions, /class="text-muted">尚未选择<\/span>/)
assert.match(executions, /:deep\(\.el-dialog\) \{[^}]*max-height: calc\(100vh - 48px\);/)
assert.match(executions, /:deep\(\.el-dialog__body\) \{[^}]*overflow-x: hidden;/)
assert.doesNotMatch(executions, /ElMessage\.warning\('加载执行集详情失败，部分数据可能不正确'\)/)
assert.doesNotMatch(interfaces, /ElMessageBox\.alert\(msg, 'cURL 解析失败'/)
assert.match(environments, /status_code/)
assert.doesNotMatch(environments, /ElMessage\.success\('调试成功'\)/)
assert.match(requestUtil, /res\.message/)

const aiGenerationButton = interfaces.match(/<el-button[^>]*@click="openInterfaceCaseGeneration"[^>]*>[\s\S]*?<\/el-button>/)?.[0]
assert.ok(aiGenerationButton, 'AI生成用例按钮应存在')
assert.match(aiGenerationButton, /AI生成用例/)
assert.doesNotMatch(aiGenerationButton, /:icon=|<el-icon/)
assert.doesNotMatch(interfaces, /openAiImportDialog|AI智能导入/)
assert.match(interfaces, /<el-dropdown[^>]*@command="handleImportCommand"/)
assert.match(interfaces, /<el-dropdown-item command="file">文件导入<\/el-dropdown-item>/)
assert.match(interfaces, /<el-dropdown-item command="curl">cURL导入<\/el-dropdown-item>/)
const actionsRow = interfaces.match(/<div class="interface-toolbar-row interface-actions-row">[\s\S]*?<div class="interface-table-scroll"/)?.[0]
assert.ok(actionsRow, '接口工具栏应保留完整的操作行')
for (const label of ['查询', '重置', '新建接口', '导入', 'AI生成用例', '批量操作', '操作记录', '工作流指引']) assert.match(actionsRow, new RegExp(label))
const actionOrder = ['handleSearch', 'resetSearch', 'handleCreateInterface', 'handleImportCommand', 'openInterfaceCaseGeneration', 'handleBatchCommand', 'openImportLogDrawer', 'workflowGuideVisible']
for (let i = 1; i < actionOrder.length; i += 1) {
  assert.ok(actionsRow.indexOf(actionOrder[i - 1]) < actionsRow.indexOf(actionOrder[i]), `${actionOrder[i - 1]} 应排在 ${actionOrder[i]} 前面`)
}
assert.match(interfaces, /@row-dblclick="handleDebug"/)
assert.match(interfaces, /const handleDebug = \(row, column, event\) => \{[\s\S]*?column\?\.type === 'selection'[\s\S]*?return/)
assert.match(interfaces, /ensureDebugEnvironment,/)
assert.match(interfaces, /useInterfaceDebug\([\s\S]*?ensureDebugEnvironment[\s\S]*?\)/)
const debugFromDialogSource = interfaces.slice(interfaces.indexOf('const debugFromDialog'), interfaces.indexOf('const handleDebug'))
assert.match(debugFromDialogSource, /if \(!ensureDebugEnvironment\(\)\) return[\s\S]*?debugDialogVisible\.value = true/)
const rowDebugSource = interfaces.slice(interfaces.indexOf('const handleDebug'), interfaces.indexOf('const sendDebugRequest'))
assert.match(rowDebugSource, /if \(!ensureDebugEnvironment\(\)\) return[\s\S]*?debugDialogVisible\.value = true/)
assert.doesNotMatch(batchGenerationDialog, /v-model="preparingVisible"/)
assert.match(batchGenerationDialog, /:loading="preparing"/)
const generationWizard = batchGenerationDialog.match(/<el-dialog[\s\S]*?class="ai-generation-wizard-dialog"[\s\S]*?<\/el-dialog>/)?.[0]
assert.ok(generationWizard, 'AI生成应使用统一五步向导 Dialog')
assert.match(generationWizard, /title="选择接口"/)
assert.match(generationWizard, /title="生成模式"/)
assert.match(generationWizard, /title="生成中"/)
assert.match(generationWizard, /title="预览确认"/)
assert.match(generationWizard, /title="保存成功"/)
assert.match(generationWizard, /<InterfaceCaseGenerationScopePanel/)
assert.match(generationWizard, /<AiGenerationModePickerDialog[\s\S]*embedded/)
assert.match(generationWizard, /class="generation-progress-dialog-body"[\s\S]*?<AiOperationProgress[\s\S]*:embedded="true"/)
assert.doesNotMatch(batchGenerationDialog, /class="generation-result-notice"/)
assert.doesNotMatch(batchGenerationDialog, /class="generation-ai-summary"/)
assert.doesNotMatch(batchGenerationDialog, /class="generation-result-count-note"/)
assert.match(generationWizard, /class="generation-result-runtime"[\s\S]*?class="generation-result-stats"/)
assert.doesNotMatch(batchGenerationDialog, /class="generation-result-loading"/)
const startGenerationSource = batchGenerationDialog.slice(
  batchGenerationDialog.indexOf('async function startGeneration'),
  batchGenerationDialog.indexOf('function onModelsRefreshed'),
)
assert.match(startGenerationSource, /wizardStep\.value = 3/)
assert.match(startGenerationSource, /const result = await batchGeneration\.run[\s\S]*?generationResult\.value = result[\s\S]*?wizardStep\.value = 4/)
assert.doesNotMatch(batchGenerationDialog, /settingsVisible|generationDialogVisible|resultVisible/)
assert.match(operationProgress, /class="ai-loading-card-head"/)
assert.match(operationProgress, /src="\/favicon\.svg"/g)
assert.match(operationProgress, /embedded: \{ type: Boolean, default: false \}/)
assert.match(operationProgress, /is-embedded/)
assert.match(batchGenerationDialog, /const generationLoadingTitle = computed\(/)
assert.match(batchGenerationDialog, /selectedMode\.value === 'main' \? '系统正在生成基础用例'/)
assert.match(batchGenerationDialog, /:title="wizardTitle"/)
assert.match(batchGenerationDialog, /const wizardTitle = computed\([\s\S]*?AI生成用例结果/)
assert.doesNotMatch(batchGenerationDialog, /title="批量生成用例(?:结果)?"/)
assert.match(generationModePicker, /:title="dialogTitle"[\s\S]*?align-center/)
const generationSettingsDialog = generationModePicker.match(/<el-dialog[\s\S]*?<\/el-dialog>/)?.[0]
assert.ok(generationSettingsDialog, '生成设置应使用独立 Dialog')
assert.doesNotMatch(generationSettingsDialog, /\btop=/)
assert.match(batchGenerationDialog, /\.generation-progress-dialog-body\s*\{[\s\S]*?align-items: center[\s\S]*?min-height: 0/)
assert.match(batchGenerationDialog, /\.generation-result-message\s*\{[\s\S]*?display: flex/)
assert.match(batchGenerationDialog, /\.result-stat\s*\{[\s\S]*?flex-direction: column/)
assert.match(batchGenerationDialog, /const shouldConfirm = !!previewId\.value && !saved\.value && \([\s\S]*?generatedCaseCount\.value > 0/)
assert.doesNotMatch(batchGenerationDialog, /batchGeneration\.usedCalls\.value > 0/)
assert.match(batchGenerationDialog, /generationResult\.value\.outcome === 'failed'[\s\S]*?return `\$\{source\}用例生成失败`/)
assert.match(batchGenerationDialog, /saved\.value = true[\s\S]*?wizardStep\.value = 5/)
assert.match(batchGenerationDialog, /@click="goToModeStep">上一步<\/el-button>/)
assert.match(batchGenerationDialog, /const isGenerationCanceled = computed\(/)
assert.match(batchGenerationDialog, /if \(isGenerationCanceled\.value\) return 'warning'/)
assert.match(batchGenerationDialog, /if \(isGenerationCanceled\.value\) \{[\s\S]*?return `已处理/)
assert.match(batchGenerationDialog, /const retryGenerationIds = computed\(/)
assert.match(batchGenerationDialog, /generationResult\.value\?\.retryIds/)
assert.match(batchGenerationDialog, /v-if="canRetryGeneration"[\s\S]*?重试失败接口/)
assert.match(batchGenerationDialog, /class="generation-failure-details"/)
assert.doesNotMatch(batchGenerationDialog, /is-generating/)
assert.match(batchGenerationDialog, /ai-generation-wizard-dialog\.is-result-step \.ai-generation-wizard-body\)\s*\{[\s\S]*?overflow:\s*hidden;/)
assert.doesNotMatch(batchGenerationDialog, /ai-generation-wizard-dialog\.is-result-step \.ai-generation-wizard-body\)\s*\{[\s\S]*?overflow-y:\s*auto;/)
assert.doesNotMatch(batchGenerationDialog, /class="ai-operation-loading-mask generation-result-loading"/)
assert.match(generationWizard, /<el-button @click="batchGeneration\.stop">停止生成<\/el-button>/)
assert.doesNotMatch(batchGenerationDialog, /class="ai-operation-loading-actions"[\s\S]*?停止生成/)
assert.match(batchGenerationDialog, /class="case-preview-dialog-body"/)
assert.match(batchGenerationDialog, /selectedCaseKeys/)
assert.match(batchGenerationDialog, /selectedCaseCount/)
assert.match(batchGenerationDialog, /:disabled="generating \|\| !previewId \|\| !selectedCaseCount"/)
assert.match(batchGenerationDialog, /保存新增用例（\{\{ selectedCaseCount \}\}）/)
assert.match(batchGenerationDialog, /saved \? \(saveReport\?\.new_case_count \|\| 0\) : '-'/)
assert.doesNotMatch(batchGenerationDialog, /本次生成 \{\{ generatedCaseCount \}\} 个，其中 \{\{ duplicateGeneratedCaseCount \}\} 个用例重复，不会重复保存，预计新增 \{\{ saveableCaseCount \}\} 个。/)
assert.doesNotMatch(batchGenerationDialog, /class="generation-result-count-note"/)
assert.doesNotMatch(batchGenerationDialog, /const duplicateGeneratedCaseCount = computed\(/)
assert.match(batchGenerationDialog, /:show-pending-notice="false"/)
assert.match(batchGenerationDialog, /@run="runEditingCase"/)
assert.match(batchGenerationDialog, /<DebugPanel/)
assert.match(batchGenerationDialog, /runTestCase/)
assert.match(batchGenerationDialog, /buildPreviewRunPayload/)
assert.match(batchGenerationDialog, /const caseRunVisible = ref\(false\)/)
assert.match(batchGenerationDialog, /:before-close="handleWizardBeforeClose"/)
assert.doesNotMatch(batchGenerationDialog, /@update:model-value="handleResultVisibility"/)
assert.match(batchGenerationDialog, /function handleWizardBeforeClose\(done\)/)
assert.match(batchGenerationDialog, /useAiOperationTimer/)
assert.match(batchGenerationDialog, /<Timer \/>/)
assert.match(batchGenerationDialog, /generationElapsedText/)
assert.match(operationProgress, /class="ai-operation-loading-time ai-operation-loading-time--breathing"/)
assert.doesNotMatch(batchGenerationDialog, /已耗时 \{\{ generationElapsedText \}\}/)
assert.match(operationProgress, /class="ai-loading-badge ai-loading-badge--breathing"/)
assert.match(operationProgress, /@keyframes ai-operation-badge-breathe/)
assert.match(operationProgress, /\.ai-loading-badge--breathing \{[\s\S]*animation: ai-operation-badge-breathe/)
assert.match(batchGenerationDialog, /selectedMode === 'main' \? '系统生成中' : 'AI生成中'/)
assert.match(operationProgress, /\.ai-operation-loading-time \{[\s\S]*font-size: 16px;[\s\S]*font-weight: 600/)
assert.match(operationProgress, /\.ai-operation-loading-time-icon \{ font-size: 16px; \}/)
assert.match(batchGenerationDialog, /class="generation-result-runtime"/)
assert.match(batchGenerationDialog, /generationHintIndex\.value % hints\.length/)
assert.doesNotMatch(batchGenerationDialog, /return `\$\{rotatingHint\} 当前第 \$\{currentBatch\}\/\$\{totalBatches\} 批，已处理 \$\{doneInterfaces\}\/\$\{totalInterfaces\} 个接口。`/)
assert.match(batchGenerationDialog, /\.result-stat-clickable:not\(:disabled\)\s*\{[\s\S]*background:/)
assert.match(batchGenerationDialog, /v-model="casePreviewVisible"/)
assert.match(batchGenerationDialog, /@click="openCasePreview\('all'\)"/)
assert.match(batchGenerationDialog, /@click="openCasePreview\('selected'\)"/)
assert.match(batchGenerationDialog, /v-model="casePreviewKeyword"/)
assert.match(batchGenerationDialog, /<el-pagination[\s\S]*:total="casePreviewTotal"/)
assert.match(batchGenerationDialog, /casePreviewPageSize/)
assert.match(batchGenerationDialog, /casePreviewPagedCases/)
assert.doesNotMatch(batchGenerationDialog, /<div class="generation-case-preview">/)
assert.match(batchGenerationDialog, /selected_cases: selectedCasesPayload\.value/)
assert.match(batchGenerationDialog, /全选/)
assert.match(batchGenerationDialog, /casePreviewSelectableKeys/)
assert.match(batchGenerationDialog, /casePreviewLoading/)
assert.match(batchGenerationDialog, /@click="searchCasePreview"/)
assert.match(batchGenerationDialog, /selected_keys: \[\.\.\.selectedCaseKeys\.value\]/)
assert.match(batchGenerationDialog, /excluded_keys: \[\.\.\.removedCaseKeys\.value\]/)
assert.match(batchGenerationDialog, /generation-save-result/)
assert.match(batchGenerationDialog, /用例保存成功/)
assert.doesNotMatch(batchGenerationDialog, /ElMessage\.success\(result\?\.summary/)
assert.match(aiImportApi, /searchInterfaceCaseGenerationCases/)
assert.match(aiImportApi, /interface-case-generation\/cases\/search/)
assert.match(generationEndpoint, /selected_cases: dict\[str, list\] \| None = Field\(/)
assert.match(generationEndpoint, /selected_cases=req\.selected_cases/)
assert.match(generationEndpoint, /class InterfaceCaseGenerationCasesQueryRequest\(BaseModel\)/)
assert.match(generationEndpoint, /@router\.post\("\/interface-case-generation\/cases\/search"\)/)
assert.match(generationEndpoint, /selectable_keys/)
assert.match(generationEndpoint, /excluded_keys/)
assert.match(generationPersist, /selected_cases: dict\[str, list\] \| None = None/)
assert.match(generationPersist, /selected_cases\.get\(temp_id\)/)
assert.match(generationComposable, /Array\.isArray\(data\?\.interfaces\)/)
assert.match(generationComposable, /生成服务未返回有效的用例结果/)
assert.match(generationComposable, /return summarize\('failed', failedDetails\.length\s*\?\s*\(failedDetails\[0\]\?\.reason \|\| ''\)/)
assert.match(batchGenerationDialog, /String\(item\?\.temp_id \|\| ''\)/)
assert.match(batchGenerationDialog, /returned\.has\(String\(item\.temp_id\)\)[\s\S]*?returned\.get\(String\(item\.temp_id\)\)/)
assert.match(generationEndpoint, /if isinstance\(iface\.get\("generated_cases"\), list\) and iface\["generated_cases"\]:/)
assert.match(generationEndpoint, /iface\["generated_cases"\] = build_system_generated_case\(iface\)/)
assert.match(generationModePicker, /watch\(\(\) => \[props\.modelValue, props\.loading\][\s\S]*?if \(open && !loading && refreshedCandidates\.value === null\) syncDraft\(\)/)
assert.match(testCaseEditDialog, /v-if="props\.showInfo && hasPersistedMetadata"/)
assert.match(testCaseEditDialog, /watch\(\[\(\) => props\.modelValue, hasPersistedMetadata\]/)
assert.match(interfaceDetailDialog, /v-if="props\.showInfo && hasPersistedMetadata"/)
assert.match(interfaceDetailDialog, /watch\(\[\(\) => props\.modelValue, hasPersistedMetadata\]/)
assert.match(importDialog, /<InterfaceDetailDialog[\s\S]*:show-info="false"/)
assert.match(interfaces, /<InterfaceEditDialog/)
assert.match(interfaceEditDialog, /<el-tab-pane v-if="props\.showInfo && props\.model\.id" label="信息" name="info">/)
assert.match(interfaceEditDialog, /<RecordMetadataTable :record="props\.model" \/>/)
assert.match(interfaceEditDialog, /<template #status>[\s\S]*label="接口状态"[\s\S]*<el-select v-model="props\.model\.workflow_status"[\s\S]*workflow_status/)
const interfaceInfoTab = interfaceEditDialog.match(/<el-tab-pane v-if="props\.showInfo && props\.model\.id" label="信息" name="info">([\s\S]*?)<\/el-tab-pane>/)?.[1] || ''
assert.doesNotMatch(interfaceInfoTab, /接口状态|workflow_status/)
assert.match(interfaceCases, /<InterfaceEditDialog/)
assert.match(batchGenerationDialog, /value: 'main'/)
assert.match(batchGenerationDialog, /value: 'normal'/)
assert.match(batchGenerationDialog, /value: 'full'/)
assert.match(generationModePicker, /modelId: needModel\.value \? draftModelId\.value : null/)
assert.match(generationComposable, /mode: ctx\.mode\(\)/)
assert.match(generationComposable, /selected_model_id: batch\.requires_model \? ctx\.modelId\(\) : null/)
assert.match(generationPolicy, /MODE_ALLOWED_CASE_TYPES = \{[\s\S]*?"main"[\s\S]*?"normal"[\s\S]*?"full"/)

console.log('confirmed behavior fix contract test ok')
