import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const curlSource = read('../src/views/tools/Curl.vue')
const previewSource = read('../src/components/CurlRequestPreview.vue')
const codePreviewSource = read('../src/components/CodePreview.vue')
const requestDetailSource = read('../src/components/ExecutionRequestDetail.vue')
const responseDetailSource = read('../src/components/ExecutionResponseDetail.vue')

assert.equal((curlSource.match(/<CurlRequestPreview/g) || []).length, 1)
assert.doesNotMatch(curlSource, /const CodePreview = defineComponent/)
assert.match(curlSource, /import CodePreview from '@\/components\/CodePreview\.vue'/)
assert.match(curlSource, /import ExecutionRequestDetail from '@\/components\/ExecutionRequestDetail\.vue'/)
assert.match(curlSource, /import ExecutionResponseDetail from '@\/components\/ExecutionResponseDetail\.vue'/)
assert.match(curlSource, /<ExecutionRequestDetail/)
assert.match(curlSource, /<ExecutionResponseDetail/)
assert.match(curlSource, /path-params-text/)
assert.match(previewSource, /<CodePreview/)
assert.match(previewSource, /请求方法/)
assert.match(previewSource, /查询参数/)
assert.match(previewSource, /请求头/)
assert.match(requestDetailSource, /label="查询参数" name="params"/)
assert.match(requestDetailSource, /label="路径参数" name="path"/)
assert.match(requestDetailSource, /label="请求体" name="body"/)
assert.match(requestDetailSource, /label="请求头" name="headers"/)
assert.match(responseDetailSource, /label="响应体" name="body"/)
assert.match(responseDetailSource, /label="响应头" name="headers"/)
assert.match(codePreviewSource, /复制内容/)
assert.doesNotMatch(codePreviewSource, /<span class="code-label">内容<\/span>/)
assert.match(curlSource, /<template #headers>[\s\S]*<CodePreview :content="displayResponseHeaders" \/>/)

assert.match(curlSource, /type="success" @click="handleRun"/)
assert.doesNotMatch(curlSource, /const openRunDialog = () =>/)
assert.match(curlSource, /const activeRunTab = ref\('response'\)/)
assert.match(curlSource, /<el-tab-pane label="响应结果" name="response">/)
assert.doesNotMatch(curlSource, /<el-tab-pane v-if="runResult" label="响应结果"/)
assert.match(curlSource, /暂无响应/)
assert.match(curlSource, /runDialogVisible\.value = true/)
assert.doesNotMatch(curlSource, /<el-button type="primary" @click="handleRun"/)

console.log('cURL 请求预览组件化结构校验通过')
