import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const importDialog = read('../src/components/ImportDialog.vue')
const importTargetPicker = read('../src/components/ImportTargetPicker.vue')
const importModeBar = read('../src/components/ImportModeBar.vue')
const importFileUpload = read('../src/components/ImportFileUpload.vue')
const interfaces = read('../src/views/Interfaces.vue')
const resultSummaryPath = new URL('../src/components/ImportResultSummary.vue', import.meta.url)
const targetPathDialogPath = new URL('../src/components/ImportTargetPathDialog.vue', import.meta.url)
const importApi = read('../../backend/api/v1/endpoints/import_api.py')

assert.match(importDialog, /<el-dialog[^>]*title="文件导入"/)
assert.match(importDialog, /<ImportResultSummary[^>]*>/)
assert.match(importDialog, /'import-dialog-shell--result': step === 3/)
assert.match(importDialog, /<ImportTargetPicker[\s\S]*class="target-config-block"/)
assert.match(importTargetPicker, /ref="pickerNewInput"/)
assert.match(importTargetPicker, /function focusNewPathInput\(\)[\s\S]*pickerNewInput\.value\?\.focus\(\)/)
assert.match(importTargetPicker, /@click="switchPickerMode\('new'\)"/)
assert.match(importTargetPicker, /function switchPickerMode\(mode\)[\s\S]*mode === 'new'[\s\S]*focusNewPathInput\(\)/)
assert.match(importTargetPicker, /<el-dialog[\s\S]*@opened="focusNewPathInput"/)
assert.match(importDialog, /const emit = defineEmits\(\['update:modelValue', 'done', 'closed', 'debug-interface', 'result-ready'\]\)/)
assert.match(importDialog, /\.import-dialog\s+:deep\(\.el-result__subtitle\)\s*\{[^}]*width:\s*100%/s)
// 第一步保持紧凑，只展示导入目标与服务配置
assert.doesNotMatch(importDialog, /importNotice/)
assert.doesNotMatch(importDialog, /class="upload-step-alert"/)
assert.match(importDialog, /<div class="target-config-grid">[\s\S]*class="target-config-item"[\s\S]*服务标识（可选）/)
assert.match(importDialog, /<ImportServiceSelect[\s\S]*v-model="defaultServiceKey"[\s\S]*:services="services"/)
assert.match(importDialog, /\.target-config-grid \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
assert.doesNotMatch(importDialog, /:title="importGuide"/)
assert.doesNotMatch(importDialog, /:title="serviceNotice"/)
assert.doesNotMatch(importDialog, /本次将导入到接口集：/)
assert.doesNotMatch(importDialog, /class="form-tip">用于追踪导入来源/)
assert.match(importDialog, /\.parse-error-summary\s*\{[^}]*justify-content:\s*flex-start/s)
// 第二步顶部只留「模式按钮 + 核心数字」，旧的卡片、判重长句和概览 alert 都不再常驻
assert.doesNotMatch(importDialog, /strategy-option|strategy-tip|duplicateStrategyTip|previewOverview|previewListTip|dedup-hidden-tip/)
assert.match(importModeBar, /<div class="mode-bar">[\s\S]*class="mode-bar-label">导入模式/)
assert.match(importModeBar, /<el-radio-button value="full"[^>]*>全量模式/)
assert.match(importModeBar, /<el-radio-button value="incremental"[^>]*>增量模式/)
assert.match(importModeBar, /\.mode-bar-stats \{[^}]*margin-left: auto/)
assert.doesNotMatch(importModeBar, /\.el-table--scrollable-y \.el-scrollbar__wrap::\-webkit-scrollbar/)
assert.doesNotMatch(importModeBar, /\.el-table--scrollable-y \.el-scrollbar__thumb\s*\{[^}]*min-height:/s)
assert.doesNotMatch(importModeBar, /\.import-table-scroll \.el-table__body-wrapper \.el-scrollbar__wrap\s*\{[^}]*overflow-x:\s*auto/s)
assert.doesNotMatch(importModeBar, /\.import-table-scroll \.el-table__body-wrapper \.el-scrollbar__wrap::\-webkit-scrollbar/)
assert.match(importModeBar, /\.import-dialog-shell--result \.el-dialog__body\s*\{[^}]*overflow:\s*visible/s)
assert.match(importModeBar, /\.import-dialog-shell--result \.import-dialog-body\s*\{[^}]*min-height:\s*0[^}]*overflow:\s*visible/s)
assert.match(importDialog, /:global\(\.import-dialog-shell--result\) \.import-dialog-body\s*\{[^}]*min-height:\s*0/s)
assert.match(importDialog, /<template #footer>\s*<ImportDialogFooter v-if="step === 2">/)
assert.match(importDialog, /@click="handleExecute\(false\)"[\s\S]*?>导入接口<\/el-button>/)
assert.match(importDialog, /@click="handleExecute\(true\)"[\s\S]*?>导入接口 \+ 生成用例<\/el-button>/)
assert.match(importDialog, /step\.value = 3\s+emit\('result-ready'\)/)
assert.match(importDialog, /\.result-pane\s*\{[^}]*min-height:\s*0[^}]*padding:\s*24px 0 12px/s)
assert.match(importDialog, /<ImportDialogFooter v-else-if="step === 1">/)
assert.match(importDialog, /<ImportDialogFooter v-else>\s*<el-button type="primary" @click="\$emit\('done'\)">完成<\/el-button>/)
const resultFooterStart = importDialog.indexOf('<ImportDialogFooter v-else>')
const resultFooterEnd = importDialog.indexOf('</ImportDialogFooter>', resultFooterStart)
assert.doesNotMatch(importDialog.slice(resultFooterStart, resultFooterEnd), />关闭</)
assert.match(importDialog, /const createdCases = ref\(false\)/)
assert.match(importDialog, /create_test_cases: withCases/)
assert.match(importDialog, /:title="hasChanges \? \(createdCases \? '导入接口 \+ 生成用例完成' : '导入接口完成'\) : noChangeTitle"/)
assert.match(importDialog, /value: r\.new_test_cases \|\| 0/)
assert.match(importDialog, /value: r\.updated_test_cases \|\| 0/)
assert.match(interfaces, /@done="onImportDone"\s+@result-ready="onImportResultReady"/)
assert.match(interfaces, /const onImportDone = \(\) => \{\s*importDialogVisible\.value = false\s*\}/)
assert.match(interfaces, /const onImportResultReady = \(\) => \{\s*loadTree\(\)\s*loadInterfaces\(activeCollection\.value\?\.id \|\| null\)\s*\}/)
assert.match(importFileUpload, /下载 Excel 模板/)
assert.match(importFileUpload, /download-template/)
for (const label of ['新增接口集', '新增接口', '更新接口', '新增用例', '更新用例']) {
  assert.match(importDialog, new RegExp(label))
}

assert.match(interfaces, /<el-dialog[^>]*title="cURL 导入"/)
assert.match(interfaces, /<el-dialog[^>]*class="curl-import-dialog"/)
assert.doesNotMatch(interfaces, /:title="curlImportReport \? '导入结果'/)
assert.match(interfaces, /<ImportResultSummary[^>]*>/)
assert.match(interfaces, /<ImportTargetPicker[\s\S]*v-model:mode="curlTargetMode"/)
assert.match(interfaces, /\.curl-import-dialog\s+:deep\(\.el-result__subtitle\)\s*\{[^}]*width:\s*100%/s)
assert.equal((interfaces.match(/:title="curlImportNotice"/g) || []).length, 2)
assert.match(interfaces, /const curlImportNotice = computed\(/)
assert.doesNotMatch(interfaces, /:title="`共解析 /)
for (const label of ['新增接口集', '新增接口', '更新接口']) {
  assert.match(interfaces, new RegExp(label))
}
assert.doesNotMatch(interfaces, /本次将导入到接口集：/)
assert.doesNotMatch(interfaces, /查看层级/)
assert.doesNotMatch(interfaces, /<el-alert[^>]*:title="serviceImportNotice"/)

assert.ok(existsSync(resultSummaryPath), '共享结果统计组件应存在')
assert.ok(existsSync(targetPathDialogPath), '导入目标层级弹窗应复用共享组件')
if (existsSync(resultSummaryPath)) {
  const resultSummary = readFileSync(resultSummaryPath, 'utf8')
  assert.match(resultSummary, /v-for="stat in stats"/)
  assert.match(resultSummary, /class="import-result-stat"/)
  assert.match(resultSummary, /class="import-result-value"/)
  assert.match(resultSummary, /\.import-result-summary\s*\{[\s\S]*max-width:/)
  assert.match(resultSummary, /\.import-result-summary\s*\{[\s\S]*margin:\s*0 auto/)
  assert.match(resultSummary, /grid-template-columns:\s*repeat\(5,\s*minmax\(112px,\s*1fr\)/)
  assert.match(resultSummary, /white-space:\s*nowrap/)
  assert.match(resultSummary, /@media\s*\(max-width:\s*900px\)/)
  assert.match(resultSummary, /@media\s*\(max-width:\s*600px\)/)
}
if (existsSync(targetPathDialogPath)) {
  const targetPathDialog = readFileSync(targetPathDialogPath, 'utf8')
  assert.match(targetPathDialog, /title="当前导入接口集层级"/)
  assert.match(targetPathDialog, /完整层级/)
  assert.match(targetPathDialog, /我知道了/)
}
assert.match(importApi, /"new_modules":\s*0/)
assert.match(importApi, /"new_modules":\s*report\["new_modules"\]/)

console.log('导入弹窗与结果页布局回归校验通过')
