import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const pageSource = readFileSync(new URL('../src/views/Interfaces.vue', import.meta.url), 'utf8')
const drawerSource = readFileSync(new URL('../src/components/InterfaceImportLogDrawer.vue', import.meta.url), 'utf8')

assert.match(pageSource, /<el-button @click="openImportLogDrawer">操作记录<\/el-button>/)
assert.doesNotMatch(pageSource, /导入日志/)
assert.match(pageSource, /InterfaceImportLogDrawer/)
assert.doesNotMatch(drawerSource, /<el-drawer/)
assert.match(drawerSource, /<el-dialog/)
assert.match(drawerSource, /title="操作记录"/)
assert.match(drawerSource, /暂无操作记录/)
assert.match(drawerSource, /操作记录加载失败，请重试/)
assert.doesNotMatch(drawerSource, /接口导入日志|暂无导入日志|导入日志加载失败/)
assert.match(drawerSource, /width="min\(760px, calc\(100vw - 48px\)\)"/)
assert.match(drawerSource, /align-center/)
assert.match(drawerSource, /class="interface-import-log-dialog"/)
assert.doesNotMatch(drawerSource, /class="log-operator-tag"/)
assert.match(drawerSource, /class="log-operator"[\s\S]*log\.user_avatar[\s\S]*log\.user_name/)
assert.match(drawerSource, /<img v-if="log\.user_avatar"/)
assert.match(drawerSource, /log\.user_name\?\.charAt\(0\) \|\| '\?'/)
assert.match(drawerSource, /class="log-operator-avatar"/)
assert.match(drawerSource, /\.log-title-line \{[^}]*gap: 12px;[^}]*\}/)
assert.match(drawerSource, /\.dialog-body\s*\{[\s\S]*height:\s*min\([^;]+;[\s\S]*overflow:\s*hidden;[\s\S]*display:\s*flex;/)
assert.match(drawerSource, /\.dialog-scroll-content[\s\S]*flex: 1;[\s\S]*overflow-y: auto;/)
assert.match(drawerSource, /文件导入/)
assert.match(drawerSource, /cURL 导入/)
assert.match(drawerSource, /历史接口导入/)
assert.match(drawerSource, /接口删除/)
assert.match(drawerSource, /interface_delete/)
assert.match(drawerSource, /getInterfaceImportLogItems/)
assert.match(drawerSource, /detailRequestSeq/)
assert.match(drawerSource, /接口：删除 \{\{ interfaceCount\(log\) \}\} 个/)
assert.match(drawerSource, /用例：删除 \{\{ caseCount\(log\) \}\} 个/)
assert.match(drawerSource, /接口：新增 \{\{ newInterfaceCount\(log\) \}\} 个，更新 \{\{ updatedInterfaceCount\(log\) \}\} 个/)
assert.match(drawerSource, /用例：新增 \{\{ newCaseCount\(log\) \}\} 个，更新 \{\{ updatedCaseCount\(log\) \}\} 个/)
assert.match(drawerSource, /删除接口明细/)
assert.match(drawerSource, /@click="openDeleteItems\(log, 'interfaces'\)"/)
assert.match(drawerSource, /@click="openDeleteItems\(log, 'cases'\)"/)
assert.match(drawerSource, /function priorityLabel\(priority\)/)
assert.match(drawerSource, /high: '高'/)
assert.match(drawerSource, /medium: '中'/)
assert.match(drawerSource, /low: '低'/)
assert.match(drawerSource, /<el-table-column v-if="detailType !== 'interfaces'" label="优先级" width="90">[\s\S]*priorityLabel\(row\.priority\)/)
assert.match(drawerSource, /:page-sizes="\[10, 50, 100\]"/)
assert.match(drawerSource, /const pageSize = ref\(10\)/)
assert.match(drawerSource, /v-model:page-size="pageSize"/)
assert.match(drawerSource, /@size-change="handlePageSizeChange"/)
assert.match(drawerSource, /@current-change="handlePageChange"/)
assert.match(drawerSource, /formatBeijingTime\(log\.created_at\)/)
assert.match(drawerSource, /@\/utils\/beijingTime/)
assert.match(drawerSource, /暂无操作记录/)
assert.match(drawerSource, /el-timeline/)
assert.match(drawerSource, /查看 AI 导入选择/)
assert.match(drawerSource, /openAiChoice\(log\)/)
assert.match(drawerSource, /title="AI 导入选择"/)
assert.match(drawerSource, /class="ai-import-choice-dialog"/)
assert.doesNotMatch(drawerSource, /<el-collapse v-if="log\.source === 'ai'/)

console.log('接口操作记录时间轴回归校验通过')
