import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const layout = readFileSync(new URL('../src/layout/index.vue', import.meta.url), 'utf8')
const topBar = readFileSync(new URL('../src/layout/TopBar.vue', import.meta.url), 'utf8')
const router = readFileSync(new URL('../src/router/index.js', import.meta.url), 'utf8')
const models = readFileSync(new URL('../src/views/admin/AiModels.vue', import.meta.url), 'utf8')
const modelDetail = readFileSync(new URL('../src/views/admin/components/AiModelDetailDialog.vue', import.meta.url), 'utf8')
const usage = readFileSync(new URL('../src/views/admin/AiUsage.vue', import.meta.url), 'utf8')
const modelTable = models.slice(models.indexOf('<el-table :data="pageData"'), models.indexOf('</el-table>', models.indexOf('<el-table :data="pageData"')))
const usageLogTable = usage.slice(usage.indexOf('<el-table :data="logs"'), usage.indexOf('</el-table>', usage.indexOf('<el-table :data="logs"')))

assert.match(layout, /router-link v-if="isSuperAdmin" to="\/users"/)
assert.match(layout, /router-link v-if="isSuperAdmin" to="\/data-admin\/audit"/)
assert.match(layout, /<span>平台用户管理<\/span>/)
assert.match(layout, /<span>审计日志管理<\/span>/)
const navLabels = ['个人中心', '平台用户管理', 'AI模型配置', 'AI用量统计', '消息渠道管理', '消息模板管理', '执行策略管理', '问题反馈', '审计日志管理', '平台数据管理']
let previousNavIndex = -1
for (const label of navLabels) {
  const currentNavIndex = layout.indexOf(`<span>${label}</span>`)
  assert.ok(currentNavIndex > previousNavIndex, `${label} 导航顺序不正确`)
  previousNavIndex = currentNavIndex
}
assert.match(layout, /router-link to="\/model-admin\/models"/)
assert.match(layout, /AI模型配置/)
assert.match(layout, /AI用量统计/)
assert.match(layout, /消息渠道管理/)
assert.match(layout, /消息模板管理/)
assert.match(layout, /执行策略管理/)
assert.match(layout, /平台数据管理/)
assert.doesNotMatch(layout, /<span>AI配额管理<\/span>/)
assert.doesNotMatch(layout, /<span>AI调用记录<\/span>/)
assert.doesNotMatch(topBar, /command="feedback"/)
assert.match(topBar, /command="profile"/)
assert.match(topBar, /command="logout"/)
assert.match(router, /if \(!user \|\| !user\.is_superuser\) \{\r?\n\s*next\('\/'\)/)
assert.doesNotMatch(router, /to\.path === '\/model-admin\/models' \|\| to\.path === '\/model-admin\/quotas'/)
assert.match(router, /path: 'model-admin\/models\/mine'/)
assert.match(router, /path: 'model-admin\/models\/platform'/)
assert.match(router, /path: 'model-admin\/models\/users'/)
assert.match(router, /path: 'model-admin\/usage\/overview'/)
assert.match(router, /path: 'model-admin\/usage\/records'/)
assert.match(router, /const superAdminPaths = \['\/data-admin', '\/model-admin\/models\/users', '\/model-admin\/usage\/users'\]/)
assert.doesNotMatch(models, /个人模型/)
assert.doesNotMatch(modelDetail, /个人模型/)
assert.match(models, /v-model="form\.daily_limit"/)
assert.match(models, /const platformQuotaForm = reactive\(\{ daily_limit: 50 \}\)/)
assert.match(models, /const personalQuotaForm = reactive\(\{ daily_limit: 50 \}\)/)
assert.match(models, /const form = ref\(\{[\s\S]*daily_limit: 50 \}\)/)
assert.match(models, /scope: initialScope[\s\S]*daily_limit: 50 \}\r?\n  formVisible\.value = true/)
assert.doesNotMatch(models, /setAiModelWeight|使用权重|v-model="form\.weight"/)
assert.match(models, /await setAiModelQuota\(created\.id, Number\(form\.value\.daily_limit\)\)/)
assert.match(usage, /<el-tab-pane label="用量概览" name="summary" \/>/)
assert.match(usage, /<el-tab-pane label="调用记录" name="logs" \/>/)
assert.match(usage, /<el-table-column label="平台模型额度"/)
assert.match(usage, /<el-option label="我的模型" value="personal" \/>/)
assert.match(usage, /function quotaSnapshot\(/)
assert.match(usage, /function platformQuotaDisplay\(/)
assert.match(usage, /platformQuotaDisplay\(\{\s*daily_limit:/)
assert.match(modelTable, /label="我的模型额度（次）"/)
assert.match(modelTable, /<el-table :data="pageData" :fit="true"/)
assert.match(modelTable, /label="模型名称" prop="model" width="160"/)
assert.match(modelTable, /label="我的模型额度（次）" min-width="160"/)
assert.match(modelTable, /label="平台模型额度（次）" min-width="150"/)
assert.match(modelTable, /<el-button link class="quota-cell-button" @click="openPersonalQuotaDialog\(row\)">/)
assert.match(modelTable, /label="操作" width="190" align="center" fixed="right"/)
assert.doesNotMatch(modelTable, /@click="openPersonalQuotaDialog\(row\)"[^>]*>设置额度/)
assert.match(modelTable, /<el-tag v-if="isUserModelsTab" :type="row\.enabled \? 'success' : 'info'" size="small">\{\{ row\.enabled \? '启用' : '停用' \}\}<\/el-tag>/)
assert.match(modelTable, /<el-switch\s+v-else\s+:model-value="row\.enabled"/s)
assert.doesNotMatch(modelTable, /label="日额度"/)
assert.doesNotMatch(modelTable, /label="今日剩余"/)
assert.match(modelTable, /<el-tag :type="personalQuotaTagType\(row\)"/)
assert.match(modelTable, /<el-tag :type="platformQuotaTagType\(row\)"/)
assert.match(models, /function quotaTagType\(/)
assert.match(models, /\.full-table \{ width: 100%; min-width: 0; \}/)
assert.match(models, /\.model-table \{ min-width: 1175px; \}/)
assert.match(modelTable, /label="模型别名" prop="name" width="130"/)
assert.match(modelTable, /label="模型名称" prop="model" width="160"/)
assert.match(modelTable, /label="能力检测" min-width="110"/)
assert.match(modelTable, /label="余额查询" min-width="140"/)
assert.match(models, /row\.can_query_balance && row\.balance_query_enabled && row\.balance_query_configured/)
assert.doesNotMatch(models, /row\.can_query_balance && row\.balance_query_enabled && row\.balance_query_configured && row\.balance_query_status === 'passed'/)
assert.match(models, /response_preview/)
assert.match(models, /billing-response-json/)
assert.match(models, /testAiModelBillingDraft/)
assert.match(models, /canConfigureBalance/)
assert.match(models, /仅模型创建人可以配置和测试余额接口/)
assert.match(models, /仅模型创建人可以查询余额/)
assert.match(usageLogTable, /label="平台额度"/)
assert.match(usageLogTable, /label="我的额度"/)
assert.match(usageLogTable, /:type="quotaSnapshotTagType\(row\)"/)
assert.match(usage, /function quotaSnapshotTagType\(/)
assert.match(models, /@change="handleFormEnabledChange"/)
assert.match(models, /:disabled="saveLoading"/)
assert.match(models, /function handleFormEnabledChange\(/)
assert.doesNotMatch(models, /当前模型未完成能力检测，保存后将保持停用状态/)
assert.match(models, /能力检测用于辅助检查配置，不影响模型启用/)
assert.match(models, /v-if="capabilityTesting"[^>]*@click="cancelCapabilityTest"[^>]*>终止检测<\/el-button>/)
assert.match(models, /capabilityAbortController\?\.abort\(\)/)
assert.match(models, /if \(controller\.signal\.aborted\) return/)
assert.match(models, /testAiModelCapabilities\(editingId\.value, requestConfig\)/)
assert.match(models, /testAiModelCapabilitiesDraft\(payload, requestConfig\)/)
assert.match(models, /await resetAiModelCapabilities\(modelId/)
assert.doesNotMatch(usage, /label="来源"/)
assert.match(usage, /v-if="canViewAllAiData"[^>]*label="姓名\/手机号"/)
assert.match(usage, /\.stats-left[^\n]*min-height: 0/)
