import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const view = readFileSync(new URL('../src/views/ParameterSetDetail.vue', import.meta.url), 'utf8')
const api = readFileSync(new URL('../src/api/parameterSet.js', import.meta.url), 'utf8')
const itemsEndpoint = readFileSync(new URL('../../backend/api/v1/endpoints/parameter_sets_routers/items.py', import.meta.url), 'utf8')
const setsEndpoint = readFileSync(new URL('../../backend/api/v1/endpoints/parameter_sets_routers/sets.py', import.meta.url), 'utf8')

assert.match(api, /getParameterSetItems/)
assert.match(api, /batchDeleteParameterItems/)
assert.match(api, /batchAddParameterItems/)
assert.match(view, /getParameterSetItems/)
assert.match(view, /page-sizes="\[10, 50, 100\]"/)
assert.match(view, /<template #empty><GlobalEmpty text="暂无数据" \/><\/template>/)
assert.match(view, /handleDeleteAll/)
assert.match(view, /delete_all_in_scope/)
assert.doesNotMatch(view, /filterParameterItems|const filteredItems/)
assert.doesNotMatch(view, /\$\{key\} (?:变量引用|引用)/)
assert.match(view, /搜索接口 URL \/ 接口名称 \/ 用例名称/)
assert.match(view, /visibleInterfaceGroups/)
assert.match(view, /同 Key·值不同/)
assert.match(view, /parameterLocationLabel\(m\)/)
assert.match(view, /class="candidate-source-detail-location">参数位置：\{\{\s*parameterLocationLabel\(src\)\s*\}\}/)
assert.match(view, /class="interface-group-open-detail"/)
assert.match(view, /class="param-target-open-detail"/)
const caseTargetHead = view.match(/<div class="param-target-head">[\s\S]*?<\/div>/)?.[0] || ''
assert.ok(caseTargetHead.indexOf('param-target-name') < caseTargetHead.indexOf('param-target-open-detail'), '用例详情入口应紧跟用例名称')
assert.match(itemsEndpoint, /batch-delete/)
assert.match(itemsEndpoint, /items\/batch/)
assert.match(itemsEndpoint, /delete_all_in_scope/)
assert.match(view, /batchAddParameterItems/)
assert.doesNotMatch(view, /for \(const row of rowsToAdd\) \{\s*await batchAddParameterItems/s)
assert.match(setsEndpoint, /source_keyword/)
assert.match(setsEndpoint, /interface_name/)
assert.match(setsEndpoint, /class ReplacementGroup/)
assert.match(setsEndpoint, /data\.replacements/)
assert.match(view, /replacements: keys\.map\(/)
assert.doesNotMatch(view, /for \(let i = 0; i < keys\.length; i\+\+\) \{\s*const group = groups\[keys\[i\]\]/s)

console.log('参数项后端查询分页、批量删除与接口聚合参数化回归契约通过')
