import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const projectPage = readFileSync(new URL('../src/views/Projects.vue', import.meta.url), 'utf8')
const userStore = readFileSync(new URL('../src/stores/user.js', import.meta.url), 'utf8')
const permissions = readFileSync(new URL('../../backend/core/permissions.py', import.meta.url), 'utf8')
const environmentApi = readFileSync(new URL('../../backend/api/v1/endpoints/environments.py', import.meta.url), 'utf8')
const reportApi = readFileSync(new URL('../../backend/api/v1/endpoints/reports.py', import.meta.url), 'utf8')
const interfacesPage = readFileSync(new URL('../src/views/Interfaces.vue', import.meta.url), 'utf8')
const interfaceCasesPage = readFileSync(new URL('../src/views/InterfaceCases.vue', import.meta.url), 'utf8')
const parameterSetApi = readFileSync(new URL('../src/api/parameterSet.js', import.meta.url), 'utf8')
const parameterSetDetail = readFileSync(new URL('../src/views/ParameterSetDetail.vue', import.meta.url), 'utf8')
const aiImportCase = readFileSync(new URL('../src/utils/aiImportCase.js', import.meta.url), 'utf8')
const requestConfigTabs = readFileSync(new URL('../src/components/RequestConfigTabs.vue', import.meta.url), 'utf8')

assert.doesNotMatch(projectPage, /queueSearch|setTimeout\(.*loadProjects/)
assert.match(projectPage, /is_public:\s*true/)
assert.doesNotMatch(projectPage, /ElMessage\.error\(['"]保存失败['"]\)/)
assert.match(userStore, /try\s*\{[\s\S]*JSON\.parse\(savedUser\)[\s\S]*catch/)
assert.match(permissions, /def can_access_project\(/)
assert.match(environmentApi, /data=_serialize_environment\(db_env,\s*current_user\)/)
assert.match(environmentApi, /_serialize_environment\(env,\s*current_user\)/)
assert.match(reportApi, /Report\.created_at\.desc\(\), Report\.id\.desc\(\)/)
assert.match(interfacesPage, /getInterface\b/)
assert.match(interfacesPage, /const handleEdit = async \(row\)/)
assert.match(interfacesPage, /await getInterface\(row\.id\)/)
assert.match(interfaceCasesPage, /getTestCase\b/)
assert.match(interfaceCasesPage, /async function openEdit\(tc\)/)
assert.match(interfaceCasesPage, /await getTestCase\(tc\.id\)/)
assert.match(interfaceCasesPage, /创建时间：\{\{ formatCaseTime\(tc\.created_at\) \}\}/)
assert.match(interfaceCasesPage, /修改时间：\{\{ formatCaseTime\(tc\.updated_at\) \}\}/)
assert.match(interfaceCasesPage, /import \{ formatBeijingTime \} from '@\/utils\/beijingTime'/)
assert.match(interfaceCasesPage, /const formatCaseTime = \(value\) => value \? formatBeijingTime\(value\) : '-'/)
assert.match(parameterSetApi, /export function addItem\(psId, data, options = \{\}\)/)
assert.match(parameterSetApi, /export function addItem\(psId, data, options = \{\}\) \{[\s\S]*?data,\s*\.\.\.options[\s\S]*?\n\}/)
assert.match(parameterSetDetail, /await batchAddParameterItems\(psId\.value,[\s\S]*?\}, \{ skipSuccessToast: true \}\)/)
assert.match(parameterSetDetail, /ElMessage\.success\(`已加入 \$\{rowsToAdd\.length\} 个参数`\)/)
// 断言只按值比较：数据类型字段运行时不参与判定，已整体移除，别再加回来
assert.doesNotMatch(aiImportCase, /expected_type/)
assert.doesNotMatch(requestConfigTabs, /expected_type/)
assert.doesNotMatch(aiImportCase, /expected_type|findMissingAssertionTypes|applyAssertionTypeToMissing|assertion-type-check-message-box/)

console.log('platform bugfix contract test ok')
