import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const generateDialog = read('../src/views/test-workbench/components/TestCaseGenerateDialog.vue')
const sourceSelector = read('../src/views/test-workbench/components/TestCaseSourceSelector.vue')
const executionDialog = read('../src/views/test-workbench/components/WorkbenchExecutionDialog.vue')
const assetListPage = read('../src/views/test-workbench/components/WorkbenchAssetListPage.vue')
const workbench = read('../src/views/TestWorkbench.vue')
const requirementPage = read('../src/views/test-workbench/components/RequirementManagementPage.vue')
const requirementTabsPage = read('../src/views/test-workbench/pages/WorkbenchRequirementPage.vue')
const mergedRequirementPage = read('../src/views/test-workbench/pages/WorkbenchMergedRequirementPage.vue')
const scopeSelector = read('../src/views/test-workbench/components/WorkbenchScopeSelectorDialog.vue')
const requirementSchema = read('../../backend/schemas/test_workbench.py')
const requirementRouter = read('../../backend/api/v1/endpoints/test_workbench_routers/requirements.py')
const bugRouter = read('../../backend/api/v1/endpoints/test_workbench_routers/bugs.py')
const workbenchSchema = read('../../backend/schemas/test_workbench.py')
const contentBlock = read('../src/views/test-workbench/components/ConversationContentBlock.vue')
const messageCard = read('../src/views/test-workbench/components/RefinementMessageCard.vue')
const assetForm = read('../src/views/test-workbench/components/WorkbenchAssetFormDialog.vue')
const bugDialog = read('../src/views/test-workbench/components/WorkbenchBugDialog.vue')
const aiModels = read('../src/views/admin/AiModels.vue')
const aiUsage = read('../src/views/admin/AiUsage.vue')
const users = read('../src/views/Users.vue')
const auditLogs = read('../src/views/AuditLogs.vue')
const layout = read('../src/layout/index.vue')
const projects = read('../src/views/Projects.vue')
const router = read('../src/router/index.js')
const interfaces = read('../src/views/Interfaces.vue')
const executions = read('../src/views/Executions.vue')
const reports = read('../src/views/Reports.vue')
const parameterSets = read('../src/views/ParameterSets.vue')
const messageChannels = read('../src/views/admin/MessageChannels.vue')
const messageTemplates = read('../src/views/admin/MessageTemplates.vue')
const schedulePolicies = read('../src/views/SchedulePolicies.vue')
const workbenchApi = read('../src/api/testWorkbench.js')
const requestSource = read('../src/utils/request.js')
const workbenchPageHeader = read('../src/views/test-workbench/components/WorkbenchPageHeader.vue')
const workbenchPages = Object.fromEntries([
  ['数据看板', '../src/views/test-workbench/pages/WorkbenchDashboardPage.vue'],
  ['系统管理', '../src/views/test-workbench/pages/WorkbenchSystemPage.vue'],
  ['版本管理', '../src/views/test-workbench/pages/WorkbenchVersionPage.vue'],
  ['需求管理', '../src/views/test-workbench/pages/WorkbenchRequirementPage.vue'],
  ['用例管理', '../src/views/test-workbench/pages/WorkbenchTestCasePage.vue'],
  ['Bug 管理', '../src/views/test-workbench/pages/WorkbenchBugPage.vue'],
  ['遗留项管理', '../src/views/test-workbench/pages/WorkbenchLegacyPage.vue'],
  ['待办事项', '../src/views/test-workbench/pages/WorkbenchPendingPage.vue'],
].map(([title, path]) => [title, read(path)]))
const generatePrompt = read('../../backend/docs/prompt/test_workbench_test_case_generation.md')
const preflightPrompt = read('../../backend/docs/prompt/test_workbench_test_case_preflight.md')
const mergeRefinementPrompt = read('../../backend/docs/prompt/requirement_merge_refinement.md')

assert.match(workbenchApi, /getWorkbenchTestCaseSources = \(id, params\) => request\(\{[\s\S]*paramsSerializer: \{ indexes: null \}/)
assert.match(generateDialog, /const loadPreferredSources = async \(\) =>/)
assert.match(generateDialog, /await loadPreferredSources\(\)/)
assert.match(sourceSelector, /return result/)
assert.match(sourceSelector, /:indeterminate="isPagePartiallySelected"/)
assert.match(sourceSelector, /const togglePageSelection = checked =>/)
assert.doesNotMatch(sourceSelector, /source-selector__selected/)
assert.doesNotMatch(sourceSelector, /selectedGroups/)

assert.match(executionDialog, /v-model="form\.actual_result"/)
assert.match(executionDialog, /v-model="form\.remark"/)
assert.match(executionDialog, /if \(props\.correctingId \|\| result !== 'failed'\) \{[\s\S]*props\.form\.submit_bug = false/)
assert.match(executionDialog, /props\.form\.submit_bug = true/)

assert.match(assetListPage, /import WorkbenchExecutionDialog from/)
assert.match(assetListPage, /import WorkbenchBugDialog from/)
assert.match(assetListPage, /<WorkbenchExecutionDialog/)
assert.match(assetListPage, /<WorkbenchBugDialog/)
assert.match(assetListPage, /compact-toolbar.*\['system', 'version', 'legacy_item'\]/)
assert.match(assetListPage, /'dense-toolbar': \['test_case', 'bug'\]\.includes\(assetType\)/)
assert.match(assetListPage, /const openSingleExecution = row => \{\s*singleExecutionDialog\.testCase = row/)
assert.doesNotMatch(assetListPage, /const openSingleExecution = row => \{\s*selectedRows\.value = \[row\]\s*openBatchExecution\(\)/)
assert.match(assetListPage, /await createWorkbenchExecution\(/)
assert.match(assetListPage, /singleExecutionForm\.result === 'failed' && singleExecutionForm\.submit_bug/)
assert.match(assetListPage, /openExecutionBug\(execution\)/)
assert.match(assetListPage, /const openExecutionBug = execution => \{[\s\S]*submitBugDialog\.visible = true/)
assert.match(assetListPage, /class="batch-execution-content"/)
assert.match(assetListPage, /\.batch-execution-options \{[^}]*margin-top:/)

assert.match(workbench, /const applyRouteScope = async \(\) =>/)
assert.match(workbench, /watch\(\(\) => \[route\.query\.system_id, route\.query\.version_id\]/)
assert.match(layout, /watch\(projectId, \(val\) => \{[\s\S]*if \(isProjectPage\.value && val\)/)
assert.match(layout, /if \(isProjectPage\.value && projectId\.value\) \{ fetchProject\(\); loadEnvironments\(\); loadParameterSets\(\) \}/)
assert.match(layout, /project-config-card/)
assert.match(layout, /projectConfigDialogVisible/)
assert.match(layout, /const saveProjectConfig = \(\) =>/)
assert.match(projects, /router\.push\(`\/project\/\$\{row\.id\}\/dashboard`\)/)
assert.match(router, /path: 'project:\?id|path: 'project\/:id'[\s\S]*redirect: '\/project\/:id\/dashboard'/)

assert.match(requirementPage, /const currentListDeletePayload = \(\) =>/)
assert.doesNotMatch(requirementPage, /openPreview\(row\)/)
assert.match(requirementPage, /withCount\('批量确认', selectedRows\.length\)/)
assert.match(requirementPage, /withCount\('AI 合并', selectedRows\.length\)/)
assert.match(requirementPage, /withCount\('批量删除', selectedRows\.length\)/)
assert.match(requirementPage, /withCount\('全部删除', total\)/)
assert.match(requirementPage, /\.toolbar-buttons \{[^}]*flex-wrap: wrap;[^}]*gap: 10px 12px;/s)
assert.doesNotMatch(requirementPage, /\.toolbar-buttons \{[^}]*overflow-x: auto;/s)
assert.match(requirementPage, /style="width: 150px"/)
assert.match(requirementPage, /style="width: 110px"/)
assert.match(requirementPage, /style="width: 210px"/)
assert.match(assetListPage, /query-actions > \.el-form-item__content[^}]*flex-wrap: wrap;[^}]*gap: 10px 12px;/s)
assert.doesNotMatch(assetListPage, /\.all-cases-toolbar \{ overflow-x: auto;/)
assert.match(assetListPage, /用例标题.*style="width: 140px"/s)
assert.match(assetListPage, /优先级.*style="width: 100px"/s)
assert.match(assetListPage, /创建时间.*style="width: 190px"/s)
assert.match(assetListPage, /确认状态.*style="width: 110px"/s)
assert.match(assetListPage, /执行状态.*style="width: 120px"/s)
assert.match(assetListPage, /\.query-actions :deep\(\.el-button\) \{ flex: 0 0 auto; margin: 0; white-space: nowrap;/)
assert.match(assetListPage, /\.list-toolbar :deep\(\.el-form\) \{ width: 100%; display: flex; flex-wrap: wrap;/)
assert.match(assetListPage, /\.list-toolbar :deep\(\.query-actions\) \{ display: flex; flex: 0 0 auto; width: auto; margin-right: 0;/)
assert.match(assetListPage, /\.dense-toolbar :deep\(\.query-actions\) \{ display: flex; flex: 0 0 100%; width: 100%; margin-right: 0;/)
assert.doesNotMatch(assetListPage, /\.compact-toolbar :deep\(\.query-actions\) \{ display: flex; width: 100%;/)
assert.match(assetListPage, /padding: 12px 16px 12px;/)
assert.match(assetListPage, /\.list-toolbar :deep\(\.el-form\) \{ width: 100%; display: flex; flex-wrap: wrap; align-items: center; row-gap: 12px;/)
assert.match(assetListPage, /\.list-toolbar :deep\(\.el-form-item\) \{ margin-bottom: 0;/)
assert.match(assetListPage, /'all-cases-toolbar': assetType === 'test_case' && confirmTab === 'all'/)
assert.match(assetListPage, /\.all-cases-toolbar :deep\(\.el-form\) \{ display: flex; flex-wrap: wrap;/)
assert.match(assetListPage, /padding: 12px 16px 12px;/)
assert.match(assetListPage, /row-gap: 12px;/)
assert.match(requirementPage, /padding: 12px 16px 12px;/)
assert.match(requirementPage, /\.toolbar-buttons \{[^}]*gap: 10px 12px;/s)
assert.match(aiModels, /\.toolbar-button-item \{ flex: 0 0 auto; width: auto;/)
assert.doesNotMatch(aiModels, /\.toolbar-button-item \{[^}]*flex-basis: 100%;/s)
assert.match(aiModels, /\.toolbar-buttons \{[^}]*flex-wrap: wrap;[^}]*gap: 10px 12px;/s)
assert.match(aiUsage, /class="stats-filter-actions"/)
assert.match(aiUsage, /class="log-search-actions"/)
assert.match(aiUsage, /class="stats-filter-bar list-toolbar-frame"/)
assert.match(aiUsage, /class="log-search-form list-toolbar-frame"/)
const statsUserRowFilter = aiUsage.match(/if \(activeStatsTab\.value === 'users'\) \{\s*if \(row\.user_id\) \{([\s\S]*?)\r?\n    \}\r?\n  \} else if/)
assert.ok(statsUserRowFilter)
assert.match(statsUserRowFilter[1], /delete query\.userName/)
assert.match(statsUserRowFilter[1], /addQueryValue\(query, 'phone', row\.phone\)/)
assert.doesNotMatch(statsUserRowFilter[1], /row\.user_name/)
const applyLogQuerySection = aiUsage.match(/function applyLogQuery\(\) \{([\s\S]*?return true\r?\n\})/)
assert.ok(applyLogQuerySection)
assert.match(applyLogQuerySection[1], /const queryPhone = readQueryValue\('phone'\) \|\| ''/)
assert.match(applyLogQuerySection[1], /keyword: readQueryValue\('keyword'\) \|\| queryPhone/)
assert.match(applyLogQuerySection[1], /modelScope: readQueryValue\('modelScope'\) \|\| ''/)
assert.doesNotMatch(aiUsage, /statsCallerType/)
assert.doesNotMatch(aiUsage, /statsPeriod/)
const statsLogQuerySection = aiUsage.match(/function buildStatsLogQuery\(row\) \{([\s\S]*?return query\r?\n\})/)
assert.ok(statsLogQuerySection)
assert.doesNotMatch(statsLogQuerySection[1], /getStatsPeriodRange|startDate|endDate/)
assert.match(statsUserRowFilter[1], /delete query\.callerType/)
assert.match(aiUsage, /timeRange: showSummary\.value \? \[\] : appliedFilters\.timeRange/)
assert.match(users, /class="search-actions"/)
assert.match(users, /canCreateUser\(userStore\.userInfo\)[\s\S]*添加用户/)
assert.match(auditLogs, /class="search-actions"/)
assert.match(mergedRequirementPage, /<el-table-column prop="title" label="需求标题" width="220" show-overflow-tooltip>/)
assert.match(mergedRequirementPage, /<el-table-column prop="created_at" label="创建时间" width="190">[\s\S]*class="created-time"/)
assert.match(mergedRequirementPage, /<el-table-column prop="creator_name" label="创建人" min-width="110" show-overflow-tooltip>/)
assert.doesNotMatch(mergedRequirementPage, /<el-table-column prop="creator_name" label="创建人" width="110" show-overflow-tooltip>/)
assert.match(mergedRequirementPage, /<div class="table-actions">[\s\S]*:disabled="row\.confirm_status === 'confirmed'"/)
assert.doesNotMatch(mergedRequirementPage, /<el-button v-if="row\.confirm_status !== 'confirmed'" link type="warning"/)
assert.match(mergedRequirementPage, /\.created-time \{[^}]*white-space: nowrap;/)
assert.match(assetListPage, /withCount\('批量确认', selectedDraftCases\.length\)/)
assert.match(assetListPage, /withCount\('全部确认', total\)/)
assert.match(assetListPage, /withCount\('批量删除', selectedRows\.length\)/)
assert.match(assetListPage, /withCount\('批量取消确认', selectedConfirmedCases\.length\)/)
assert.match(assetListPage, /withCount\('批量执行', selectedConfirmedCases\.length\)/)
assert.match(assetListPage, /withCount\('全部删除', total\)/)
assert.match(assetListPage, /<el-table-column v-if="\['test_case', 'bug'\]\.includes\(assetType\)" type="selection"/)
assert.match(assetListPage, /<el-button v-if="assetType === 'bug'" type="danger" plain :disabled="!selectedRows\.length" @click="batchDeleteBugs">\{\{ withCount\('批量删除', selectedRows\.length\) \}\}<\/el-button>/)
assert.match(assetListPage, /const batchDeleteBugs = async \(\) =>/)
assert.match(assetListPage, /batchDeleteWorkbenchBugs\(/)
assert.match(workbenchSchema, /class TWBugBatchOperate\(BaseModel\):/)
assert.match(bugRouter, /@router\.post\("\/bugs\/batch-delete"\)/)
assert.match(scopeSelector, /\.scope-filters \{[^}]*display: grid;[^}]*grid-template-columns:/)
assert.match(scopeSelector, /\.scope-filters :deep\(\.el-input\), \.scope-filters :deep\(\.el-select\) \{ width: 100%; \}/)
assert.match(scopeSelector, /\.scope-filters__actions[^}]*white-space: nowrap;/)
assert.match(requirementSchema, /title: str \| None = None/)
assert.match(requirementRouter, /def _append_requirement_batch_delete_filters\(conditions: list, model, data: TWRequirementBatchDelete\)/)
assert.match(requirementRouter, /_append_requirement_batch_delete_filters\(scope_conditions, TWRequirement, data\)/)
assert.match(requirementRouter, /_append_requirement_batch_delete_filters\(conditions, TWCompletedRequirement, data\)/)

assert.match(contentBlock, /copyable: Boolean/)
assert.match(contentBlock, /v-if="copyable"/)
assert.match(messageCard, /:copyable="copyable"/)

assert.match(executionDialog, /<el-form-item label="场景"><el-input v-model="editForm\.scenario"/)
assert.match(executionDialog, /<el-form-item label="用例类型"><el-select v-model="editForm\.case_type"/)

assert.match(workbenchApi, /getWorkbenchProjectUsers = \(id\) => request\(\{ url: `\/test-workbench\/projects\/\$\{id\}\/users`/)
assert.doesNotMatch(assetForm, /getUsers\(/)
assert.doesNotMatch(assetListPage, /getUsers\(/)
assert.doesNotMatch(bugDialog, /getUsers\(/)
assert.doesNotMatch(bugDialog, /label="验证人"/)
const createBugPayload = assetForm.match(/bug: creating \? \(\) => createWorkbenchBug\(([^)]*)\)/)
assert.ok(createBugPayload)
assert.doesNotMatch(createBugPayload[1], /verifier_id/)
assert.doesNotMatch(requestSource, /res\.code === 403 \? '权限不足'/)
assert.doesNotMatch(workbenchPageHeader, /<p v-if="description">\{\{ description \}\}<\/p>/)
for (const [title, source] of Object.entries(workbenchPages)) {
  assert.match(source, new RegExp(`<WorkbenchPageHeader[\\s\\S]*title="${title}"`))
  assert.doesNotMatch(source, /<WorkbenchPageHeader[^>]*description=/)
}

const requirementAiSection = requirementRouter.match(/async def ask_requirement_ai_stream[\s\S]*?(?=@router\.post\("\/requirements\/\{requirement_id\}\/ai-refine\/compose)/)
const requirementComposeSection = requirementRouter.match(/async def compose_requirement_ai_stream[\s\S]*?(?=@router\.post\("\/requirements\/\{requirement_id\}\/ai-refine\/compare)/)
const requirementCompareSection = requirementRouter.match(/async def compare_requirement_ai_result_stream[\s\S]*?(?=@router\.post\("\/requirements\/\{requirement_id\}\/ai-refine\/save)/)
const requirementSaveSection = requirementRouter.match(/async def save_requirement_ai_result[\s\S]*/)
assert.ok(requirementAiSection && requirementComposeSection && requirementCompareSection && requirementSaveSection)
assert.match(requirementAiSection[0], /if data\.initial_content is not None:[\s\S]*?ensure_manage_workbench_record/)
assert.doesNotMatch(requirementComposeSection[0], /ensure_manage_workbench_record/)
assert.doesNotMatch(requirementCompareSection[0], /ensure_manage_workbench_record/)
assert.doesNotMatch(requirementSaveSection[0], /ensure_manage_workbench_record/)

assert.match(assetForm, /remote-method="searchRequirements"/)
assert.match(assetForm, /const searchRequirements = async \(keyword\) =>/)
assert.match(executionDialog, /<div v-if="item\.actual_result" class="execution-history__detail">[\s\S]*<div v-if="item\.remark" class="execution-history__detail">/)
assert.match(requirementPage, /\.toolbar-form \{ display: flex; align-items: flex-start; flex-wrap: wrap;/)
assert.match(requirementPage, /background: #f8fafc;/)
assert.match(mergedRequirementPage, /background: #f8fafc;/)
assert.match(requirementTabsPage, /<WorkbenchContentCard>[\s\S]*<el-tabs v-model="activeTab"/)
assert.doesNotMatch(requirementPage, /<WorkbenchContentCard>/)
assert.doesNotMatch(mergedRequirementPage, /<WorkbenchContentCard>/)
assert.match(requirementTabsPage, /\.requirement-tabs :deep\(\.el-tabs__header\) \{[^}]*margin: 0 0 16px;[^}]*padding-bottom: 8px;[^}]*border-bottom: 1px solid #ebeef5;/s)
assert.match(requirementTabsPage, /\.requirement-tabs :deep\(\.el-tabs__nav-wrap\)::after \{ display: none; \}/)
assert.match(requirementTabsPage, /\.requirement-tabs :deep\(\.el-tabs__item\) \{[^}]*height: 34px;[^}]*line-height: 34px;[^}]*font-size: 14px;[^}]*font-weight: 500;[^}]*color: #606266;/s)
assert.match(requirementTabsPage, /\.requirement-tabs :deep\(\.el-tabs__item\.is-active\) \{ color: #409eff; font-weight: 600; \}/)

assert.match(layout, /\.main :deep\(\.list-toolbar-frame\) \{[\s\S]*background: #f8fafc;/)
assert.match(layout, /\.main\.is-admin-module :deep\(\.search-area\),[\s\S]*background: #f8fafc;/)
assert.match(layout, /\.main\.is-admin-module :deep\(\.admin-tabs-shell \.list-toolbar\) \{[\s\S]*background: #f8fafc;/)
for (const source of [interfaces, executions, reports, parameterSets, messageChannels, messageTemplates, schedulePolicies]) {
  assert.match(source, /list-toolbar-frame/)
}

assert.doesNotMatch(generateDialog, /用例类型完全一致，请核对测试覆盖/)
assert.match(generatePrompt, /等价类/)
assert.match(generatePrompt, /边界值/)
assert.match(generatePrompt, /状态迁移/)
assert.match(generatePrompt, /幂等/)
assert.match(preflightPrompt, /首轮必须一次性列全/)
assert.match(mergeRefinementPrompt, /首轮.*尽可能完整列出所有独立且有测试价值的问题/)

console.log('workbench regression fixes test ok')
